# Generated by Django 4.2.4 on 2023-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='v_action',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='v_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=10),
        ),
    ]
