# Generated by Django 4.2.4 on 2023-09-16 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_quotes_applied_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
