# Generated by Django 4.2.4 on 2023-09-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_vendor_v_action_alter_vendor_v_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='v_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='reject', max_length=10),
        ),
    ]
