# Generated by Django 4.2.4 on 2023-09-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_vendor_v_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
