# Generated by Django 4.2.4 on 2023-09-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_quotes_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
