# Generated by Django 4.2.4 on 2023-09-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_adminuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='v_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
