# Generated by Django 4.2.4 on 2023-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_vendor_v_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfplist',
            name='action',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rfplist',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='open', max_length=10),
        ),
    ]
