# Generated by Django 4.2.4 on 2023-09-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_rfplist_action_alter_rfplist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfplist',
            old_name='rfplist_id',
            new_name='id',
        ),
    ]
