# Generated by Django 4.2.4 on 2023-09-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_rfplist_id_rfplist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfplist',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfplist',
            name='item_desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfplist',
            name='vendors',
            field=models.ManyToManyField(to='users.vendor'),
        ),
    ]
