# Generated by Django 4.2.4 on 2023-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rfplist_category_rfplist_item_desc_rfplist_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='approve', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Office Decor', 'Office Decor'), ('Furniture', 'Furniture')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
