# Generated by Django 4.2.4 on 2023-09-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_category_c_action_alter_category_c_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='item_desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='rfp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.rfplist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotes',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.vendor'),
        ),
        migrations.AlterField(
            model_name='rfplist',
            name='vendors',
            field=models.ManyToManyField(related_name='rfp_lists', to='users.vendor'),
        ),
    ]
