# Generated by Django 4.2.4 on 2023-09-07 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_quotes_item_desc_quotes_rfp_alter_quotes_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfplist',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_rfps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
