# Generated by Django 4.2.4 on 2023-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rfplist_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='c_action',
            field=models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], default='activate', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='c_name',
            field=models.CharField(max_length=100),
        ),
    ]
