# Generated by Django 4.2.4 on 2023-09-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_category_c_action_alter_category_c_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_id',
            new_name='category_id',
        ),
    ]
