# Generated by Django 4.2.4 on 2023-09-09 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_vendor_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='rfplist',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='quotes',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rfplist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
